"""fix unique attribute on Phrase

Revision ID: 103218f4148e
Revises: 3a82e5acac6f
Create Date: 2023-04-20 11:03:47.505843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103218f4148e'
down_revision = '3a82e5acac6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'language', ['primary_language_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'language', ['secondary_language_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phrase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'language', ['primary_language_id'], ['id'])
        batch_op.create_foreign_key(None, 'language', ['secondary_language_id'], ['id'])

    # ### end Alembic commands ###
