"""add new models

Revision ID: dc2faca5ea5d
Revises: 3b99aa44c406
Create Date: 2023-04-11 15:47:36.480081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2faca5ea5d'
down_revision = '3b99aa44c406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit1_quiz1', sa.Boolean(), nullable=True),
    sa.Column('unit1_quiz2', sa.Boolean(), nullable=True),
    sa.Column('unit1_quiz3', sa.Boolean(), nullable=True),
    sa.Column('unit2_quiz1', sa.Boolean(), nullable=True),
    sa.Column('unit2_quiz2', sa.Boolean(), nullable=True),
    sa.Column('unit2_quiz3', sa.Boolean(), nullable=True),
    sa.Column('unit3_quiz1', sa.Boolean(), nullable=True),
    sa.Column('unit3_quiz2', sa.Boolean(), nullable=True),
    sa.Column('unit3_quiz3', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primary_language_id', sa.Integer(), nullable=False),
    sa.Column('secondary_language_id', sa.Integer(), nullable=False),
    sa.Column('primary', sa.String(length=50), nullable=False),
    sa.Column('secondary', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['primary_language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['secondary_language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary'),
    sa.UniqueConstraint('secondary')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrase')
    op.drop_table('activity')
    op.drop_table('language')
    # ### end Alembic commands ###
