"""initial migration

Revision ID: e19de23c8be6
Revises: 
Create Date: 2023-04-20 11:41:45.877449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19de23c8be6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit1_quiz1', sa.Boolean(), nullable=True),
    sa.Column('unit1_quiz2', sa.Boolean(), nullable=True),
    sa.Column('unit1_quiz3', sa.Boolean(), nullable=True),
    sa.Column('unit2_quiz1', sa.Boolean(), nullable=True),
    sa.Column('unit2_quiz2', sa.Boolean(), nullable=True),
    sa.Column('unit2_quiz3', sa.Boolean(), nullable=True),
    sa.Column('unit3_quiz1', sa.Boolean(), nullable=True),
    sa.Column('unit3_quiz2', sa.Boolean(), nullable=True),
    sa.Column('unit3_quiz3', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primary_language_id', sa.Integer(), nullable=False),
    sa.Column('secondary_language_id', sa.Integer(), nullable=False),
    sa.Column('primary', sa.String(length=50), nullable=False),
    sa.Column('secondary', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['primary_language_id'], ['language.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secondary_language_id'], ['language.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secondary')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrase')
    op.drop_table('activity')
    op.drop_table('user')
    op.drop_table('language')
    # ### end Alembic commands ###
